### ISSUE TITLE
Symbols in text fields causing 500 error.

### ISSUE THREAD

**Issue by MattGrayYes** [nick-prater/kronekeeper#12]
I've typed a load of symbols into text fields and I get a 500 Error !@£$%^&*()_{}:"|<>?``[];'\,./
Accented characters cause it to error, as do emoji (I know they're unlikely, but hey!)

**Comment by nick-prater** [comment]
Fixed in commit a8c9f39d3e7f2c887446e1c8a813a71d3d093990

Frankly I think krone records would be far more descriptive if we used more emoji :)
