### ISSUE TITLE
Add Block - Add Earth Block

### ISSUE THREAD

**Issue by jonwcrew** [nick-prater/kronekeeper#18]
Add option to add earth block on drop down menu with 237a and ABS. 

Maybe block appears as a different colour on the frame view e.g. red.

**Comment by nick-prater** [comment]
We'll add another database table:
- block_type
  - name (e.g. 237A, EARTH)
  - colour

We'll record the block_type for each block on the frame. When displaying the frame, we'll show each block in the relevant colour, with the name of the block_type in the top-right-hand corner.

For now, we'll stick with hard-coded functions to create each block, but I can see us moving to a system of templates.

**Comment by nick-prater** [comment]
Complete with commit 9043f587b23ef091ecb01fbafa76e4915ec9b2ca
