### ISSUE TITLE
Circuit Labels not following between blocks

### ISSUE THREAD

**Issue by jonwcrew** [nick-prater/kronekeeper#25]
Example -

Fictional Studio 1A - B06 to A01

Circuit label was added after the jumper went in.

**Comment by nick-prater** [comment]
Jon - could you please confirm the behaviour you expect with circuit labels when adding a jumper between two circuits. I've never found this intuitive in KRIS. My thinking is as follows:
- If only one has a circuit label, both circuits take on that circuit label
- If both have a circuit label, kronekeeper should prompt for which to use
- A change to circuit label should bubble through all circuits connected by jumpers, looping through multiple circuits if required. This should happen even if pairs are split through custom jumpers, e.g. for DC circuits.
- Circuit label should remain in place even when jumpers are removed.

**Comment by jonwcrew** [comment]
Agree with first three points.

4 is debatable ... the least worst solution is probably to leave the labels behind. Only other solution is to designate something as the circuit label source and when that is disconnected everything down the chain is removed .. sounds unnecessarily complicated.

**Comment by nick-prater** [comment]
Manually changing a circuit name now propagates to all other connected circuits. In block view, circuits connected on the same frame are dynamically updated.

Still to do: integrate this with jumpering.

**Comment by nick-prater** [comment]
Done - and in the process have removed a call to the server and detangled the UI event chain for adding jumpers, so the process is more responsive.
