### ISSUE TITLE
Up down keys in select jumper wire dialogue

### ISSUE THREAD

**Issue by jonwcrew** [nick-prater/kronekeeper#27]
Please make up down arrow keys work in this dialogue box.
- Adding return key select to this and the previous box have made it massively more usable .. just need to be able to move down to select another jumper wire without touching the mouse.

**Comment by nick-prater** [comment]
That should be working already... it does for me. Could you please try a hard-refresh of the page?

**Comment by jonwcrew** [comment]
Doesn't seem to work for me in Mac Chrome .. have refreshed

**Comment by jonwcrew** [comment]
Hirji suggests that other key shortcuts would be good in the jumper wire select dialogue.
 i.e. 'L' selects Red/Blue 'R' Selects Yellow/Blue etc

**Comment by nick-prater** [comment]
Problem now verified in Chrome. Looking into it...

**Comment by nick-prater** [comment]
Fixed with commit b2d49fa0985557da0eea7ba03a59c05e7e2a5e42
Unlike Safari and Firefox, Chrome does not trigger Keypress event for cursor keys, so have to trap Keydown event instead.
