### ISSUE TITLE
Block Library

### ISSUE THREAD

**Issue by jonwcrew** [nick-prater/kronekeeper#35]
Not a v1 essential .. but is something you can do in KRIS>

Ability to create a pre designed block or group of blocks for reuse.

This should sit in the account level so can bet used across any frames in that account.

**Comment by nick-prater** [comment]
You can now place templates onto a frame.
But you can't yet create templates without having database access.

Internally, a template is simply a frame with the is_template flag set. When you place a template onto another frame, it is copied, complete with blocks, circuits, colours and jumpers.

This also means that the database functionality is built to allow frames to be copied, which will be useful to keep historic records or make backups before major changes.

Next step is an interface to allow template frames to be created.

**Comment by nick-prater** [comment]
Can now add/edit templates.
