### ISSUE TITLE
Add Frame navigation buttons to block view.

### ISSUE THREAD

**Issue by jonwcrew** [nick-prater/kronekeeper#40]
Need frame navigation buttons in block view.

this could be a simple set of cursor arrow buttons to move up and down a block or left/right through columns.

Function should be duplicated on some key shortcuts if possible .. maybe control+arrow key moves block?

Add Text instructions to screen for key shortcut.

**Comment by jonwcrew** [comment]
This needs to be pretty high on the priority list .. having spent a bit of time with it not being able to navigate from within block view is very annoying.

**Comment by nick-prater** [comment]
Agreed and it's what I've been working on. Expecting this to be in place by Monday.

**Comment by nick-prater** [comment]
commit fba5003b45d3dd80d11f76f7750ba7bb74e1fc2e adds this functionality. I've just put it live on the demo system. It currently does a full page load each time the block changes. I'd like to streamline this, so that it just updates the block data, which will be faster, but that's for another issue. Holding down Control and using the arrow keys navigates around the frame block-by-block.

**Comment by jonwcrew** [comment]
This seems a bit erratic on Mac.

1) Ctrl up arrow and Ctrl down arrow are the default to activate Mission control and expose application windows .. you can turn this off in the OS and then the key press is passed to the browser.

2) Safari seems to work ok .. but I get nothing from the left and right arrows.

3) Chrome - arrow keys don't work and you only see a tick in the row drop down.

**Comment by jonwcrew** [comment]
Also if you select a location with no block your browser sticks on the word 'Loading' and you have no option but to navigate back.

**Comment by nick-prater** [comment]
Fixed Stuck loading message on positions with no block - commit 076feb588d63c58da1f3ddfc77bc7ca4354d800f - live on demo system.

It's always tricky finding key bindings that aren't already in use by browser, OS or window manager for other purposes. Any suggestions that would work better for you? Would it help to add navigation arrow buttons to the page?

Chromium on Linux is working for me, but I will track down a Mac to test there.

**Comment by jonwcrew** [comment]
Shift arrow would work.
Buttons on the page also.

**Comment by nick-prater** [comment]
Shortcut  now changed to SHIFT and arrow keys. Buttons to follow...

**Comment by jonwcrew** [comment]
That works perfectly.

Please add static text to page “Use Shift-Arrow Keys to Navigate frame”

**Comment by nick-prater** [comment]
Buttons added
Description of keyboard shortcuts added
