### ISSUE TITLE
Number of krones allowed (Height)

### ISSUE THREAD

**Issue by GaryHornbuckle** [nick-prater/kronekeeper#59]
I have tried to create a new frame that is 6 wide and 80 high, but will only allow me to go to 50. Could this be changed please?

Thanks

**Comment by nick-prater** [comment]
Fixed. Thanks for reporting. Now allows up to 150 high. You may need to refresh your browser to see the change.

**Comment by GaryHornbuckle** [comment]
Thanks Nick. That works a treat now.
