### ISSUE TITLE
Pick Jumper Destination

### ISSUE THREAD

**Issue by jonwcrew** [nick-prater/kronekeeper#8]
Jumpering, need to be able to pick jumper destination by navigating the frame and finding the destination as well as entering text directly – activate by a little pick button in the corner of the box.

**Comment by nick-prater** [comment]
I've added a context menu to each jumper field. This has options for "Jumper To Here" and "Jumper From Here". I spent quite a time trying to find the best user interface for this and, having tried several ideas, decided this was best. Let me know what you think.

**Comment by jonwcrew** [comment]
Hi Nick,

I think this is a good solution .. and a great enhancement on KRIS !

There was one thing which I didn't find immediately obvious .. 

Having selected 'jumper from here' on a circuit I was surprised to discover that this selection hangs around after the first jumper.

In some ways that is useful I guess if you wanted to add several jumpers from the same 'from'.

My feeling is that it would be more intuitive if the 'from' choice reset after the first 'to' is chosen.

**Comment by nick-prater** [comment]
I debated whether to reset the 'from' choice after placing the jumper. On reflection you are right that it's more intuitive to rest the 'from' choice. Two lines of code added. It is done :)
