### ISSUE TITLE
Navigate block with cursor keys?

### ISSUE THREAD

**Issue by jonwcrew** [nick-prater/kronekeeper#9]
You can tab key through the krone block box which is good, would be helpful if the cursor keys could navigate it too.

**Comment by nick-prater** [comment]
I'm proposing to implement only Up and Down cursor keys as left/right are used to navigate within the text fields.

**Comment by nick-prater** [comment]
In block view, Up/Down arrow keys navigate between circuit rows in block since commit 7d0ec8df25420bae474560063510dc693910a673
